"""Robot command names exposed by WaSaB AdminGUI/API."""
from __future__ import annotations

COMMAND_ALIASES = {
    "g": "pick",
    "pick": "pick",
    "p": "pose",
    "pose": "pose",
    "q": "gripper",
    "gripper": "gripper",
    "r": "random",
    "random": "random",
    "s": "servo-release",
    "servo-release": "servo-release",
    "servo_release": "servo-release",
    "k": "servo-focus",
    "servo-focus": "servo-focus",
    "servo_focus": "servo-focus",
    "f": "place",
    "place": "place",
    "m": "move",
    "move": "move",
    "a": "find-marker",
    "find-marker": "find-marker",
    "marker": "find-marker",
    "marker-search": "find-marker",
    "t": "throw",
    "throw": "throw",
    "w": "home",
    "home": "home",
    "stop": "stop",
    "halt": "stop",
    "emergency-stop": "stop",
    "emergency_stop": "stop",
    "x": "exit",
    "exit": "exit",
}
